const data = {
  letter: "A",
  entries: [
    {
      term: `AARON`,
      definition: `(enlighteMd, mountaineer)* Great-grandson of Levi (Ex. 6:16-20); eldest son of Amram by Jochebed^ of the tribe of Levi; brother of Moses and Miriam, being three years older than the great law-giver (Ex. 6:20; 7:7; Num. 26:59); born probably 1574 B. C. First mentioned in account of Moses’ vision of the burning bush (Ex. 4:14), where, realizing his lack of persuasive speech, Moses was informed by the Lord that Aaron possessed this faculty, and could speak in his name, and he regularly appeared with Moses before the Egyptian Icing, performing the miracles, by command of Moses, that confounded Pharaoh and his magicians (Ex. 7:8, etc.), Moses being fourscore, and Aaron fourscore and three, years of age when they spake unto Pharaoh (Ex. 7:7). 
     During the absence of Moses in Midian, Aaron married Elisheba (or Elizabeth), daughter of Amminadab of Judah (Ex. 6:23), who bore him four sons—Nadab, Abihu, Eleazar, and Ithamar; Eleazar becoming the father of Phinehas before Moses returned (Ex. 6:23-25). Aaron and Hur held up Moses’ hands during the battle which Joshua fought with Amalek (Ex. 17:8-13). Aaron, his four sons, and seventy elders, went part way up Mt. Sinai with Moses when he went to receive the tables of the law (Ex. 24:1, 2, 9-11). Aaron made the Golden Calf (Ex. 32:1-4). Aaron and his sons were consecrated and anointed priests, Aaron being the first to occupy the high station of high-priest, holding office for about forty years (Lev. 8:12), his priesthood being confirmed by the blossoming of the rod (Num. 17:1-10); and only he could enter the Holy of Holies, once a year (Lev. 16:2, 34). Soon after becoming high-priest, his two sons, Nadab and Abihu, were struck dead for conducting the ceremonies in an irregular manner (Lev. 10:1, 2). Subsequently to this (perhaps about B. C. 1452), an unsuccessful conspiracy was formed against Moses, Aaron, and his sons by the important chiefs, Korah of the tribe of Levi, and Dathan, Abiram and On of the tribe of Reuben (Num. 16:1-19, 35, 41; comp. Num. 26:9, 10). 
     Aaron, like Moses, was not permitted to enter the Promised Land, because of distrust shown when the rock was struck at Meribah (Num. 20:8-13). Miriam was smitten with leprosy for protesting the authority of Moses, but was later ntade whole (Num. 12).. Obeying the divine mandate, Aaron, with Moses, and his son Eleazar, ascended Mt.Hor (now called Mt, Aaron), that he should there transfer his priestly office to Eleazar (Num. 20:23-29) and then die. He reached the age of 123 years (Num. 33:39), dying about 1451 B. C. In Deut. 10:6, Aaron is reported to have died at Mosera, and to have been buried there. Mosera is not on Mt. Hor, apparently, but appears near, for Num. 33:31-37 speaks of seven stages between Moseroth (or Mosera) and Mt. Hor. 
     The Israelites mourned Aaron for thirty days. The Arabs still show the traditional site of his grave, which, in the time of Eusebius, was reputed to be situated in Petra, in the modern Wady Mousa. In Psa. 106:16, Aaron is called, **The Saint of the Lord.” Mic. 6:4 mentions Moses, Aaron, and Miriam. Aaron is mentioned in the Koran.`,
    },
    {
      term: `AARONITES`,
      definition: `The descendants of Aaron are so called in 1 Ch. 12:27, where we read that Jehoiada, their leader, with 3,700 men, also Zadok and 22 captains, joined David in Ziklag; and in 27:17, that this Zadok was their ruler afterwards; and in Lu. 1:5, that the wife of Zacharias was of the "daughters of Aaron." From Josh. 21:13-19, it appears that the Aaronites had thirteen cities assigned to them—viz., Hebron, Libnah, Jattir, Eshtemoa, Holon, Debir, Ain, Juttah, and Beth-shemesh, out of Judah and Simeon; and Gibeon, Geba, Anathoth, and Almon, out of Benjamin. The high-priesthood continued in the family of Eleazar, the third son of Aaron, until the time of Eli, B. C. 1200-1141, who was of the family of Ithamar, Aaron's youngest son, but it was restored to the house of Eleazar in the person of Zadok, who received it when Abiathar was dismissed by Solomon (I Ki. 2:35), thus fulfilling the prediction in 1 Sa. 2:30.`,
    },
  ],
};

export default data;
